server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: customer
#          uri: lb://customer-service
          uri: https://www.baidu.com
          predicates:
            - Path=/customer/**
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filter:
            - RewritePath=/product/(?<segment>.*), /$\{segment}
eureka:
  client:
    service-url:
      defaultZone: http://10.8.80.60:9001/eureka
feign:
  hystrix:
    enabled: true
