server:
  port: 8080
spring:
  application:
    name: gateway
  redis:
    host: 10.6.1.105
    port: 6379
    database: 0
    password: Regan888
eureka:
  client:
    service-url:
      defaultZone: http://10.8.80.60:9001/eureka
feign:
  hystrix:
    enabled: true